Use gdrive-datastore
caciviclab/netfile-redacted pull request #4
Opened 2023-10-18 19:29 UTC by ChenglimEar

The pypi package gdrive-datastore is now a central place for the code that allows storing our data files on Google Drive.  In this pull request, we switch over to a pip install for this code and remove it from the repository.  Additionally, dev container support has been added to ensure the required development environment is completely specified.

2023-10-21 03:00 UTC, ckingbailey requested changes
One small thing: unused import

2023-10-21 03:00 UTC, ckingbailey commented on .devcontainer/devcontainer.json
👀  This is a CodeSpaces thing? Nifty. I still need to try it out.

2023-10-21 03:00 UTC, ckingbailey commented on test_pull_from_gdrive.py
> +import os
Unneeded import `os`

2023-10-22 05:27 UTC, ChenglimEar commented on test_pull_from_gdrive.py
> +import os
removed

2023-10-22 05:33 UTC, merged